FROM python:3.9

RUN apt-get update && apt-get install -y --no-install-recommends \
      bzip2 \
      g++ \
      git \
      graphviz \
      libgl1-mesa-glx \
      libhdf5-dev \
      openmpi-bin \
      wget \
      libavdevice-dev \
      libavfilter-dev \
      libopus-dev \
      libvpx-dev \
      pkg-config \
      libsrtp2-dev \
      python3-tk && \
    rm -rf /var/lib/apt/lists/*

RUN mkdir /app

WORKDIR /app

COPY ./server.py /app
COPY ./requirements.txt /app

RUN pip install -r requirements.txt
RUN pip install python-ulid


CMD ["python", "server.py"]