version: '3'
services:

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: chat_db
      POSTGRES_USER: yashdamania
      POSTGRES_PASSWORD: yashdamania
    volumes:
      - ./make_table.sql:/docker-entrypoint-initdb.d/make_table.sql
    ports:
      - 5432:5432
    
  frontend:
    build:
      context: .
      dockerfile: Dockerfile-client
    ports:
      - 3001:3001
    depends_on:
      - postgres

  backend:
    build:
      context: .
      dockerfile: Dockerfile-server
    ports:
      - 5001:5001
    depends_on:
      - postgres
  